# Generated by Django 5.2 on 2025-08-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0002_packageattribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={"verbose_name": "Package", "verbose_name_plural": "Packages"},
        ),
        migrations.AlterField(
            model_name="package",
            name="price",
            field=models.PositiveBigIntegerField(verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="package",
            name="title",
            field=models.CharField(max_length=48, verbose_name="title"),
        ),
    ]
