# Generated by Django 5.2 on 2025-08-06 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="gateway title"),
                ),
                (
                    "gateway_request_url",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="request url",
                    ),
                ),
                (
                    "gateway_verify_url",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="verify url"
                    ),
                ),
                (
                    "gateway_code",
                    models.CharField(
                        choices=[
                            ("saman", "Saman"),
                            ("shaparak", "Shaparak"),
                            ("finotech", "Finotech"),
                            ("zarrinpal", "Zarrinpal"),
                            ("parsian", "Parsian"),
                        ],
                        max_length=12,
                        verbose_name="gateway code",
                    ),
                ),
                (
                    "is_enable",
                    models.BooleanField(default=True, verbose_name="is enabled"),
                ),
                (
                    "auth_data",
                    models.TextField(blank=True, null=True, verbose_name="auth data"),
                ),
            ],
            options={
                "verbose_name": "Gateway",
                "verbose_name_plural": "Gateways",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="invoice number"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="payment amount")),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="is paid status"),
                ),
                ("payment_log", models.TextField(blank=True, verbose_name="logs")),
                (
                    "authority",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="authority"
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="finance.gateway",
                        verbose_name="gateway",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
