# Generated by Django 5.2 on 2025-08-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="finance.payment",
            ),
        ),
    ]
