# Generated by Django 5.2 on 2025-08-08 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("purchase", "0002_alter_purchase_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="finance.payment",
            ),
        ),
    ]
