# Generated by Django 5.2 on 2025-08-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body_en_us",
            field=models.TextField(null=True, verbose_name="body"),
        ),
        migrations.AddField(
            model_name="post",
            name="body_fa",
            field=models.TextField(null=True, verbose_name="body"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en_us",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_fa",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
    ]
